### ISSUE TITLE
Hulu Clone building failed

### ISSUE THREAD

**Issue by mauricewells** [curioustushar/react-sample-projects#78]
when launching Hulu Clone via yarn start command, app runs on browser, but image isn't open

**Comment by nmanikiran** [comment]
@mauricewells Thanks for checking out the repo
here is the demo https://curioustushar.github.io/react-sample-projects/hulu-clone/

you need to rename the `.env.smaple` to `.env` and add you own key

**Comment by mauricewells** [comment]
great!

**Comment by mauricewells** [comment]
can you explain my own key?

**Comment by mauricewells** [comment]
in other words, i don't know how to set my own key at your given link

**Comment by curioustushar** [comment]
@mauricewells Here is the[ .env.sample](https://github.com/curioustushar/react-sample-projects/blob/master/hulu-clone/.env.sample) file. As @nmanikiran suggested 
"you need to rename the .env.sample to .env and add your own key".

Get API key from - https://www.themoviedb.org/settings/api

**Comment by mauricewells** [comment]
![hulu_fail](https://user-images.githubusercontent.com/96590277/148710664-ba0fe04c-a740-4d5b-8e7e-717ec6930656.png)
 when runing your code by yarn start command, the above error happens
what is the reason?
